#!/bin/bash
export CLASSPATH=".:/usr/local/lib/antlr-4.5-complete.jar:$CLASSPATH"
java -cp "/usr/local/lib/antlr-4.5-complete.jar:$CLASSPATH" org.antlr.v4.Tool -visitor $1Lexer.g4 $1Parser.g4
javac $1*.java
java org.antlr.v4.runtime.misc.TestRig $1 $2 -tokens -tree -gui $3

